### ISSUE TITLE
feat: charge gateway when recurrence is enabled

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#34]
Recurrence is one thing. Charging the customer is another. Don't forget.

If the user has two recurrences enabled, on the month that will coincide both payments, the application must be able to identify if both are meant for products on the same invoice and charge just once.

If the user has two recurrences enabled but the products are not within the same invoice, you'll be charging each invoice individually.

The invoiceId to be used on the charge process should match the amount of the recurrence. Say invoice ID 1 has 100 in amount, recurrence ID 2 (for example) should also match the 100 amount.  IF the value of the invoice does not match the value of the recurrence (or recurrences summed), DO NOT charge the customer. Create a log entry and send a mail notification saying the payment has failed.

Please rename NotificationType to NotificationTemplate. In this case, you'll be adding a new one called PAYMENT-FAILED or RECURRENCE-PAYMENT-FAILED; those are merely suggestions.

**Comment by andreasfernandes93** [comment]
## Objective

Perform the charging of invoices that have an active recurrence.

## Delivery Criteria

- **Concurrent Recurrence Charging**: If the user has two enabled recurrences that coincide in the same month, the application must charge only once if the recurrences are for products on the same invoice.
- **Charging Recurrences on Different Invoices**: If the user has two enabled recurrences for products on different invoices, the application must charge each invoice individually.
- **Correspondence between Invoice Value and Recurrence Value**: The invoice value used in the charging process must match the recurrence value (or recurrences - in case they are aggregated). If the invoice does not match any recurrence, no charge should be made.
- **Charging Error Handling**: If the invoice value does not match the recurrence value, the application must create a log entry and send an email notification informing that the payment failed or that there are no recurrences for payment.

# Action Plan
- Adjust the invoiceEntity to have a due date set 7 days after its creation (for purchase invoices and recurring invoices)

## Charge Recurring Invoices
Perform the charging of active recurrences through open invoices
- Every 24 hours, perform the following procedure:
- Get the first 100 `OrgIds` in the system that have an active status;
- Get the list of active `storeGateway`;
- For each `OrgId`:
    - For each `storeGateway`:
        - Get the list of `invoices` with `status=unpaid`, `due date on the current date`, and `storeGateway`;
            - If there are none, skip to the next `OrgId`;
        - Get the list of active `recurrences` with `charge date equal to the current date` and `storeGateway`;
            - If there are none, skip to the next `OrgId`;

        - Initialize a variable `preApprovedChargeAmount` with a value of 0;
        - For each active `recurrence` in the list obtained:
                - Get the value of the `amount` of the recurrence;
                - Add the value of the recurrence to the `preApprovedChargeAmount`;
            
        - `hasOrgBeenCharged` = false;
        - For each open `invoice` in the list obtained:
            - Check if the invoice has a total value equal to the `preApprovedChargeAmount`;
            - If yes:
                - Perform the charging using the `invoiceId`;
                - Do not update the status of the invoice to "paid" as the callback will do this.
                - Update the charge date for each recurrence to the next cycle;
                - `hasOrgBeenCharged` = true;
            - If not:
                - Skip to the next invoice.
                - Slog.Debug("InvoiceId: ", invoiceId, " was not charged because the total value is not equal to the preApprovedChargeAmount");
        - If `hasOrgBeenCharged` == false
            - Notify the user listing the main reasons why the charging was not performed and recommending to contact the support or financial team.
- Get the next 100 `OrgIds` and repeat the previous process until all `OrgIds` is processed.
---

Useful links:
[https://docs.stripe.com/recurring-payments?lang=go#use-paymentintents](https://docs.stripe.com/recurring-payments?lang=go#use-paymentintents
)
[https://docs.stripe.com/payments/checkout/save-and-reuse?payment-ui=stripe-hosted#charge-saved-payment-method](https://docs.stripe.com/payments/checkout/save-and-reuse?payment-ui=stripe-hosted#charge-saved-payment-method)
[https://docs.stripe.com/api/payment_intents/create#create_payment_intent-payment_method](https://docs.stripe.com/api/payment_intents/create#create_payment_intent-payment_method)

**Comment by andreasfernandes93** [comment]
### TODO
- [x]  Fix`NextDueDate`of orgProducts to be based on invoice's createdAt.
- [x]  Fix`NextChargeDate`of storeGatewayRecurrences to be based on invoice's createdAt.
- [x] Add ReadManyOrgIds dto for orgQueryRepo.ReadManyIds(ReadManyOrgIdsRequestDto)
    -  ReadManyOrgIdsDto {PageNumber, ItemsPerPage, OrgStatus}
    - Notes: The fields of dto is optional in ReadManyIds method, if filter from dto is nill, ReadManyIds return all orgIds from db;
- [x]  Fix InvoiceEntity - add DueDate field
- [x]  Implement watchdog for invoice recurrence charging
    - [x]  add goroutine to watchdog controller
    - [x]  add watchdog ChargeRecurringInvoicesWatchdog() controller
    - [x]  add useCase ChargeRecurringInvoices
    - [x]  add orgInvoiceCmdRepo.ChargeRecurrence(orgid) Test
    - [x]  add orgInvoiceCmdRepo.ChargeRecurrence(orgid)
- [x] Feat - implement StoreGatewayCmdRepo.UpdateRecurrenceChargeDate
---
