### ISSUE TITLE
feat: GET /v1/store/gateway/recurrence/

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#40]
When the user decides to enable recurrence during a payment, besides adding the details to the org extra fields, also create an entry on the database to register that there is that kind of recurrence enabled. That kind because each recurrence may have different values.

If the user tries to enable the recurrence for an invoice that already has a recurrence enabled, you should delete the previous recurrence and add the new one; effectively replacing the previous recurrence.

This GET here is a list of those recurrences.

**Comment by andreasfernandes93** [comment]
# Create Recurrences
## Objective
To create recurring charges when users enable recurrence during payment. Create recurrence for each billing cycle of the invoice's products.

## Delivery Criteria
* Create recurrence for each pricing cycle (priceCycle) present in the invoice
* Do not create recurrences for one-time charge products
* Do not create recurrences for invoices that already have existing recurrences

## Strategy
The creation of recurrences should occur during invoice payment. Therefore, it will happen immediately after checkout is completed and the user has enabled the "shouldEnableRecurrence" option as true.

### CreateCheckoutPayment UseCase
Steps:
- Checks if the Invoice Exists
- Checks if the user is a member of the Org that owns the invoice
- Checks if the invoice has the "unpaid" status
- Creates the CheckoutPayment.
- If ShouldEnableRecurrence was set to TRUE;
   - Creates the recurrences for each existing periodicity in the invoice (storeGatewayCmdRepo.CreateRecurrences(invoiceId))
- Returns the checkout URL.

**Comment by andreasfernandes93** [comment]
# Read Recurrences
## Objective
Get the list of recurrences from the user's org.

## Delivery Criteria
* Display only recurrences where the user is a member of the organization
* If user doesn't specify which organization's recurrences to display, use the organization where they are the account owner

## Strategy
### ReadStoreGatewayRecurrences Use Case 
Steps:
- Checks if OrgId is Null
  - If null, gets user's account primaryOrgId (orgQueryRepo.ReadPrimaryOrgByAccountId)
- Validates if user belongs to storeGatewayRecurrence's Org (uc.ValidateOrgMembership)
- Gets StoreGatewayRecurrences list (storeGatewayQueryRepo.ReadRecurrences)
- If successful, returns list and error == nil

**Comment by andreasfernandes93** [comment]
## TODO List
* [x] Create StoreGatewayRecurrence during PayInvoice route
  * [x] Add `storeGatewayCmdRepo.CreateRecurrence` to CreateCheckoutPayment UC, right after CheckoutPayment creation
  * [x] Create CreateRecurrence repo (interface)
  * [x] Create StoreGatewayRecurrence model
  * [x] Create CreateRecurrence implementation (infra repo)
* [x] Create `/v1/store/gateway/recurrence/` Route
  * [x] Controller
  * [x] UseCase
  * [x] Infra
