### ISSUE TITLE
feat(ui): admin setup

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#64]
Admin Login is the same as the already existent Login page. However, you have to check if the account has the admin read policy so you can redirect the account to /admin/ instead of /.

The setup on another hand, you must copy from the OS. It only works when there is NO admin account. Check on OS how the logic works. It's not rocket science. Don't be afraid.

**Comment by polillomm** [comment]
# Dev Report [![prShield](https://img.shields.io/badge/pull_request-merged-8957e5?style=flat-square&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iI2ZmZmZmZiIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0Ij48cGF0aCBkPSJNMTUgMTMuMjVhMy4yNSAzLjI1IDAgMSAxIDYuNSAwIDMuMjUgMy4yNSAwIDAgMS02LjUgMFptLTEyLjUgNmEzLjI1IDMuMjUgMCAxIDEgNi41IDAgMy4yNSAzLjI1IDAgMCAxLTYuNSAwWm0wLTE0LjVhMy4yNSAzLjI1IDAgMSAxIDYuNSAwIDMuMjUgMy4yNSAwIDAgMS02LjUgMFpNNS43NSA2LjVhMS43NSAxLjc1IDAgMSAwLS4wMDEtMy41MDFBMS43NSAxLjc1IDAgMCAwIDUuNzUgNi41Wm0wIDE0LjVhMS43NSAxLjc1IDAgMSAwLS4wMDEtMy41MDFBMS43NSAxLjc1IDAgMCAwIDUuNzUgMjFabTEyLjUtNmExLjc1IDEuNzUgMCAxIDAtLjAwMS0zLjUwMUExLjc1IDEuNzUgMCAwIDAgMTguMjUgMTVaIj48L3BhdGg%2BPHBhdGggZD0iTTYuNSA3LjI1YzAgMi45IDIuMzUgNS4yNSA1LjI1IDUuMjVoNC41VjE0aC00LjVBNi43NSA2Ljc1IDAgMCAxIDUgNy4yNVoiPjwvcGF0aD48cGF0aCBkPSJNNS43NSAxNi43NUEuNzUuNzUgMCAwIDEgNSAxNlY4YS43NS43NSAwIDAgMSAxLjUgMHY4YS43NS43NSAwIDAgMS0uNzUuNzVaIj48L3BhdGg%2BPC9zdmc%2B)](https://github.com/goinfinite/bz/pull/191)

_Last updated on Jul 24, 2025_

Check it on goinfinite/bz#191.

## Tasks checklist (time spent/time planned)
- [x] Implements setup API route with controller (2h/2h);
- [x] Implements setup UI route with presenter (2h/2h);
- [x] Implements setup UI page (2h/2h).

## Tasks detailed list (time spent/time planned)
**Spent:** 6h
**Planned:** 6h

- ~Implements setup API route with controller~;
  **Spent:** 2h
  **Planned:** 2h
- ~Implements setup UI route with presenter~;
  **Spent:** 2h
  **Planned:** 2h
- ~Implements setup UI page~;
  **Spent:** 2h
  **Planned:** 2h

## Important notes
No important notes for now.

## Useful links
- [Implementation of the setup controller in the Infinite OS API](https://github.com/goinfinite/os/blob/main/src/presentation/api/controller/setup.go);
- [Implementation of the setup route in the Infinite OS UI](https://github.com/goinfinite/os/blob/a6727e36e6bb2e3bac8e109da32b186fbc87b7ac/src/presentation/ui/router.go#L157C1-L165C2);
- [Implementation of the setup page in the Infinite OS UI](https://github.com/goinfinite/os/blob/main/src/presentation/ui/layout/setup/setup.templ).
