### ISSUE TITLE
feat(ui): staff overview

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#65]

**Comment by polillomm** [comment]
# Dev Report [![prShield](https://img.shields.io/badge/pull_request-not_open_yet-656c76?style=flat-square&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iI2ZmZmZmZiIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0Ij48cGF0aCBkPSJNNC43NSAxLjVhMy4yNSAzLjI1IDAgMCAxIC43NDUgNi40MTRBLjgyNy44MjcgMCAwIDEgNS41IDh2OGEuODI3LjgyNyAwIDAgMS0uMDA1LjA4NkEzLjI1IDMuMjUgMCAwIDEgNC43NSAyMi41YTMuMjUgMy4yNSAwIDAgMS0uNzQ1LTYuNDE0QS44MjcuODI3IDAgMCAxIDQgMTZWOGMwLS4wMjkuMDAyLS4wNTcuMDA1LS4wODZBMy4yNSAzLjI1IDAgMCAxIDQuNzUgMS41Wk0xNiAxOS4yNWEzLjI1IDMuMjUgMCAxIDEgNi41IDAgMy4yNSAzLjI1IDAgMCAxLTYuNSAwWk0zIDQuNzVhMS43NSAxLjc1IDAgMSAwIDMuNTAxLS4wMDFBMS43NSAxLjc1IDAgMCAwIDMgNC43NVptMCAxNC41YTEuNzUgMS43NSAwIDEgMCAzLjUwMS0uMDAxQTEuNzUgMS43NSAwIDAgMCAzIDE5LjI1Wm0xNi4yNS0xLjc1YTEuNzUgMS43NSAwIDEgMCAuMDAxIDMuNTAxIDEuNzUgMS43NSAwIDAgMC0uMDAxLTMuNTAxWm0wLTExLjVhMS43NSAxLjc1IDAgMSAwIDAtMy41IDEuNzUgMS43NSAwIDAgMCAwIDMuNVpNMjEgMTEuMjVhMS43NSAxLjc1IDAgMSAxLTMuNSAwIDEuNzUgMS43NSAwIDAgMSAzLjUgMFoiPjwvcGF0aD48L3N2Zz4%3D)]()

_Last updated on Jul 11, 2025_

Waiting for the pull request to be merged to add the task summary.

## Tasks checklist (time spent/time planned)
- [x] Add **staff** `main.templ` and `sidebar.templ` (6h30m/6h30m);
- [x] Add UI route and presenter (4h/4h);
- [x] Add UI page (8h/8h);
- [x] Test UI page (2h/2h);
- [x] Credit (14h/14h).
  _sponsored by Northon._

## Tasks detailed list (time spent/time planned)
**Spent:** 26h
**Planned:** 26h

- ~Add **staff** `main.templ` and `sidebar.templ`~;
  **Spent:** 6h30m
  **Planned:** 6h30m
- ~Add UI route and presenter~;
  **Spent:** 4h
  **Planned:** 4h
- ~Add UI page~;
  **Spent:** 8h
  **Planned:** 8h
- ~Test UI page~.
  **Spent:** 2h
  **Planned:** 2h

## Important notes
No important notes for now.

## Useful links
No useful links for now.
