### ISSUE TITLE
feat(ui): view account

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#66]

**Comment by andreasfernandes93** [comment]
# Dev Report [![prShield](https://img.shields.io/badge/pull_request-not_open_yet-656c76?style=flat-square&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iI2ZmZmZmZiIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0Ij48cGF0aCBkPSJNNC43NSAxLjVhMy4yNSAzLjI1IDAgMCAxIC43NDUgNi40MTRBLjgyNy44MjcgMCAwIDEgNS41IDh2OGEuODI3LjgyNyAwIDAgMS0uMDA1LjA4NkEzLjI1IDMuMjUgMCAwIDEgNC43NSAyMi41YTMuMjUgMy4yNSAwIDAgMS0uNzQ1LTYuNDE0QS44MjcuODI3IDAgMCAxIDQgMTZWOGMwLS4wMjkuMDAyLS4wNTcuMDA1LS4wODZBMy4yNSAzLjI1IDAgMCAxIDQuNzUgMS41Wk0xNiAxOS4yNWEzLjI1IDMuMjUgMCAxIDEgNi41IDAgMy4yNSAzLjI1IDAgMCAxLTYuNSAwWk0zIDQuNzVhMS43NSAxLjc1IDAgMSAwIDMuNTAxLS4wMDFBMS43NSAxLjc1IDAgMCAwIDMgNC43NVptMCAxNC41YTEuNzUgMS43NSAwIDEgMCAzLjUwMS0uMDAxQTEuNzUgMS43NSAwIDAgMCAzIDE5LjI1Wm0xNi4yNS0xLjc1YTEuNzUgMS43NSAwIDEgMCAuMDAxIDMuNTAxIDEuNzUgMS43NSAwIDAgMC0uMDAxLTMuNTAxWm0wLTExLjVhMS43NSAxLjc1IDAgMSAwIDAtMy41IDEuNzUgMS43NSAwIDAgMCAwIDMuNVpNMjEgMTEuMjVhMS43NSAxLjc1IDAgMSAxLTMuNSAwIDEuNzUgMS43NSAwIDAgMSAzLjUgMFoiPjwvcGF0aD48L3N2Zz4%3D)]()

_Last updated on Ago 13, 2025_

Waiting for the pull request to be merged to add the task summary.

## Tasks checklist (time spent/time planned)
- [x] Add Account View Page (10h/8h);
  - [x] Planning wireframe (35min)
  - [x] add route, adjust sideBar, add presenter.go (30min)
  - [x] add index.templ & state.js (8h)
    - [x] add tags (10min)
    - [x] account information (10min)
    - [x] update password button and modal (3h)
    - [x] update function (2h)
    - [x] personal information (2h22)
- [ ] PR Fix (3h)



## Tasks detailed list (time spent/time planned)
**Planned:** 8h
**Spent:** 10h

## Important notes
- I took a longer time to implement the logic for the ChangePass modal.  Initially, I did everything via Alpine, but I brought up the possibility of moving this logic to the backend in the update route.

## Useful links
No useful links for now.
