### ISSUE TITLE
feat(ui): org invoices index & view

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#71]

**Comment by andreasfernandes93** [comment]
# Dev Report  - Org Invoice Index

_Last updated on Ago 22, 2025_

Waiting for the pull request to be merged to add the task summary.

## Tasks checklist (time spent/time planned)

- [x] Add org invoices index (33h/10h);
  - [x] Planning wireframe (1h)
  - [x] add route, adjust sideBar, add presenter.go (1h) 
  - [x] liaison (11h)
  - [x] PaymentInvoice (10h)
    - [x] Test stripe payment (3h)
    - [x] Adjust stripe field and tests (1h30)
    - [x] add payment and payment with recurrency button with tests (1h30)
    - [x] try add payment button with checkbox to RecurrentPayment (2h30) = 3h
  - [x] index templ (3h) 
    - [x] add invoice table with pagination (2h)
    - [x] add update gateway, pay invoice, view invoice button (30min)
- [x] PR Fix (7h) 



## Tasks detailed list (time spent/time planned)

**Planned:** 10h
**Spent:** 33h

## Important notes

- Liaison (11h) — I wasted time on the liaison layer due to poor planning on how to implement that layer in the backend. Part of this time was caused by an incorrect initial implementation of the helper "readRequestInputData" in the presenter layer.
- PaymentInvoice (10h) — I started by rereading the Stripe route to refresh how we handle payments. In the tests I found a bug that cost me unnecessary time (3h for testing Stripe + 1h30 to fix = 4h30). After fixing it, I continued implementing the payment buttons: initially I planned to have a button plus a checkbox for recurring payments (2h30), but after asking in the channel the recommended approach was to use a separate button for each case.
- PR FIX (7h) — The PR fixes were requested during this week’s calls for adjustments to layout, colors, button functionality, and the new Liaison layer. I also corrected issues raised by CodeRabbit and Norton during the review.

## Useful links

No useful links for now.

**Comment by andreasfernandes93** [comment]
# Dev Report - Org Invoice View

_Last updated on Set 03, 2025_

Waiting for the pull request to be merged to add the task summary.

## Tasks checklist (time spent/time planned)

- [x] Add org invoices index (10h/8h);
  - [x] Planning wireframe (1h)
  - [x] add route, adjust sideBar, add overview link (1h) 
  - [x] Create Org and AdminOrg liaison (1h)
  - [x] Create OrgInvoice View page (2h)
  - [x] Add payment buttons and test (30min)
- [x] PR Fix ()
  - [x] Adjust layout (1h) 
  - [x] Create gatewayName helper and test (1h30)
  - [x] Adjust ReadTransactions to new pattern (30min)



## Tasks detailed list (time spent/time planned)

**Planned:** 8h
**Spent:** 10h

## Important notes

## Useful links

No useful links for now.
