### ISSUE TITLE
feat(ui): org

### ISSUE THREAD

**Issue by ntorga** [goinfinite/bz-issue-tracker#72]
This UI is for management of orgs. It must contains:
- Create org button on top of the page;
- List of orgs the user is part of;
- On each org on the table, you must have a edit and delete button;
- The columns of the table should shown only the most important information with the full information shown only on the edit modal;
- You may also have a "Log-in" button on the table row to switch the org like it's done on the orgSelector;
- The edit modal must have a list of accounts belonging to the org and a delete button next to it so the org primary account may dissociate accounts => who can see this area? Only the primary account;
- If you don't want to use the edit modal for the account mgmts, create a new button on the table called "manage accounts" and a modal for just that;

**Comment by andreasfernandes93** [comment]
# Dev Report [![prShield](https://img.shields.io/badge/pull_request-not_open_yet-656c76?style=flat-square&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iI2ZmZmZmZiIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0Ij48cGF0aCBkPSJNNC43NSAxLjVhMy4yNSAzLjI1IDAgMCAxIC43NDUgNi40MTRBLjgyNy44MjcgMCAwIDEgNS41IDh2OGEuODI3LjgyNyAwIDAgMS0uMDA1LjA4NkEzLjI1IDMuMjUgMCAwIDEgNC43NSAyMi41YTMuMjUgMy4yNSAwIDAgMS0uNzQ1LTYuNDE0QS44MjcuODI3IDAgMCAxIDQgMTZWOGMwLS4wMjkuMDAyLS4wNTcuMDA1LS4wODZBMy4yNSAzLjI1IDAgMCAxIDQuNzUgMS41Wk0xNiAxOS4yNWEzLjI1IDMuMjUgMCAxIDEgNi41IDAgMy4yNSAzLjI1IDAgMCAxLTYuNSAwWk0zIDQuNzVhMS43NSAxLjc1IDAgMSAwIDMuNTAxLS4wMDFBMS43NSAxLjc1IDAgMCAwIDMgNC43NVptMCAxNC41YTEuNzUgMS43NSAwIDEgMCAzLjUwMS0uMDAxQTEuNzUgMS43NSAwIDAgMCAzIDE5LjI1Wm0xNi4yNS0xLjc1YTEuNzUgMS43NSAwIDEgMCAuMDAxIDMuNTAxIDEuNzUgMS43NSAwIDAgMC0uMDAxLTMuNTAxWm0wLTExLjVhMS43NSAxLjc1IDAgMSAwIDAtMy41IDEuNzUgMS43NSAwIDAgMCAwIDMuNVpNMjEgMTEuMjVhMS43NSAxLjc1IDAgMSAxLTMuNSAwIDEuNzUgMS43NSAwIDAgMSAzLjUgMFoiPjwvcGF0aD48L3N2Zz4%3D)]()

_Last updated on Jul 30, 2025_

Waiting for the pull request to be merged to add the task summary.

## Tasks checklist (time spent/time planned)
- [x] Planning  (2h/2h);
- [ ] Implement Org Page (in progress/20h);
  - [x] Org Index (3h/3h)
  - [x] Org Edit Modal (13h/3h)
  - [x] Delete Org modal and buttom (1h/1h)
  - [x] Org Create Modal and Update Org Status buttom (2h/2h)
  - [x] Adjust org table with iconText (1h/1h)
  - [x] Adjust org presenter error handling with presenterErrors (1h/1h)
  - [x] Login-in buttom (2h30/3h)
  - [x] Manage account orgs modal (6h/2h)
  - [ ] Fix PR (/4h)
    - [x] Adjust buttons and iconText (1h)
    - [x] Adjust buttons manage account modal (1h)
    - [x] Revert accountIds slices and add associatedAccounts slices (1h)
    - [x] move loginToOrg() method to main state.js and adjust orgIndex state.js and orgSelectorPopupState.js (30min)
    - [x]  add orgsIndexSettings struct, adjust buttons and tailwind classes from orgsIndex (30min)
    - [x] Dev review and fix coderrabit review (2h)


## Tasks detailed list (time spent/time planned)
**Spent:**  in progress
**Planned:** 8h

- Org Index;
  **Planned:** 1h
  **Spent:** in progress
- Org Edit Modal;
  **Planned:** 3h
  **Spent:** -
- PR Fix;
  **Planned:** 3h
  **Spent:** -


## Important notes
- I underestimated the organization update form. There were several implementation details that were new to me, but I was able to accomplish them with guidance from calls and based on what has already been done in OS and EZ (13h).

## Useful links
No useful links for now.
